baseURL = "https://github.com/octoberHerr/octoberHerr.github.io"
languageCode = "zh-CN"
title = "我的技术文档"
theme = "book"

# 启用侧边栏目录
[params]
  BookTheme = "auto" # 主题模式：auto, light, dark
  BookRepo = "https://github.com/octoberHerr/octoberHerr.github.io" # 可选：显示 Git 仓库链接